[package]
name = "chronoban"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
anyhow = "1.0"
tokio = { version = "1.42", features = ["full"] }
walkdir = "2.5"
futures = "0.3"
